name: Default

on:
  push:
    branches:    
      - main
      - 'release/**'
    tags:        
      - v*
    paths:
      - '.github/workflows/default.yml'
      - 'src/**'
      - '.node-version'
      - 'package.json'
      - 'package-lock.json'
      - 'vite.config.js'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      - run: pnpm add -g web-ext
      - run: pnpm i
      - run: pnpm run build-workspaces --mode=production
        env:
          NODE_ENV: production
      - run: pnpm run build --mode=production
        env:
          NODE_ENV: production
      - run: pnpm exec web-ext lint
      - run: pnpm exec web-ext build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: error
